name: mirs260x-jazzy

services:
  jazzy:
    build:
      context: .
      network: host
    container_name: jazzy
    privileged: true
    network_mode: host
    ipc: host
    pid: host

    environment:
      - DISPLAY=${DISPLAY}
      #- XAUTHORITY=${XAUTHORITY}
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=90

    volumes:
      - type: bind
        source: "./src"
        target: "/home/developer/ws/src"
      - type: bind
        source: "/tmp/.X11-unix"
        target: "/tmp/.X11-unix"
      - build-vol:/ws/build
      - install-vol:/ws/install
      - log-vol:/mirsws/log

    devices:
      - /dev:/dev

    stdin_open: true
    tty: true
    command: bash

volumes:
  build-vol:
  install-vol:
  log-vol:
